# Generated by Django 5.0.1 on 2024-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careers_Web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_feedback',
            name='email',
        ),
        migrations.AlterField(
            model_name='career_feedback',
            name='feedback',
            field=models.CharField(max_length=420),
        ),
        migrations.AlterField(
            model_name='careers_hub',
            name='company_link',
            field=models.TextField(max_length=120),
        ),
    ]
